language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.1
    - android-25
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
  licenses:
    - android-sdk-license-5be876d5
    - android-sdk-license-c81a61d9

jdk: oraclejdk8

install:
  - true

script:
  - ./gradlew clean build check

cache:
  directories:
    - $HOME/.m2